// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qJhJbLN2Wy56BDK1v9VeHg
// Component: ekDTLgGFZZ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import BreadcrumbItem from "../../BreadcrumbItem"; // plasmic-import: nl-iwxSy9T/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_open_bootcamp_v_2_0.module.css"; // plasmic-import: qJhJbLN2Wy56BDK1v9VeHg/projectcss
import sty from "./PlasmicBreadcrumb.module.css"; // plasmic-import: ekDTLgGFZZ/css

export type PlasmicBreadcrumb__VariantMembers = {
  bg: "yes" | "no";
};

export type PlasmicBreadcrumb__VariantsArgs = {
  bg?: SingleChoiceArg<"yes" | "no">;
};

type VariantPropType = keyof PlasmicBreadcrumb__VariantsArgs;
export const PlasmicBreadcrumb__VariantProps = new Array<VariantPropType>("bg");

export type PlasmicBreadcrumb__ArgsType = {
  breadcrumbItems?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBreadcrumb__ArgsType;
export const PlasmicBreadcrumb__ArgProps = new Array<ArgPropType>(
  "breadcrumbItems"
);

export type PlasmicBreadcrumb__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultBreadcrumbProps {
  breadcrumbItems?: React.ReactNode;
  bg?: SingleChoiceArg<"yes" | "no">;
  className?: string;
}

function PlasmicBreadcrumb__RenderFunc(props: {
  variants: PlasmicBreadcrumb__VariantsArgs;
  args: PlasmicBreadcrumb__ArgsType;
  overrides: PlasmicBreadcrumb__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxbg_no]: hasVariant(variants, "bg", "no")
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <BreadcrumbItem
                breadcrumbParent={
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__eeAC
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Parent"}
                  </p.PlasmicLink>
                }
                className={classNames(
                  "__wab_instance",
                  sty.breadcrumbItem__pcwut
                )}
                parent={true}
              />

              <BreadcrumbItem
                child={["child"]}
                className={classNames(
                  "__wab_instance",
                  sty.breadcrumbItem__i2X8D
                )}
              />
            </React.Fragment>
          ),
          value: args.breadcrumbItems
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBreadcrumb__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBreadcrumb__VariantsArgs;
    args?: PlasmicBreadcrumb__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBreadcrumb__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBreadcrumb__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBreadcrumb__ArgProps,
          internalVariantPropNames: PlasmicBreadcrumb__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBreadcrumb__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBreadcrumb";
  } else {
    func.displayName = `PlasmicBreadcrumb.${nodeName}`;
  }
  return func;
}

export const PlasmicBreadcrumb = Object.assign(
  // Top-level PlasmicBreadcrumb renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicBreadcrumb
    internalVariantProps: PlasmicBreadcrumb__VariantProps,
    internalArgProps: PlasmicBreadcrumb__ArgProps
  }
);

export default PlasmicBreadcrumb;
/* prettier-ignore-end */
