// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: upY9cnzMG3kZgeoF6ecCnw
// Component: F-xRm26zTCA
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: BnsO6Lq9gm/component
import OfferCard from "../../OfferCard"; // plasmic-import: j3ZEEkH_dZ/component
import Tag from "../../Tag"; // plasmic-import: y2UxC8Idw2/component
import OfferCardDetailsItem from "../../OfferCardDetailsItem"; // plasmic-import: E8-Ct61FHc/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_job_run.module.css"; // plasmic-import: upY9cnzMG3kZgeoF6ecCnw/projectcss
import sty from "./PlasmicRelatedOffers.module.css"; // plasmic-import: F-xRm26zTCA/css

import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: m0MmFEQ7ZK/icon

export type PlasmicRelatedOffers__VariantMembers = {};

export type PlasmicRelatedOffers__VariantsArgs = {};
type VariantPropType = keyof PlasmicRelatedOffers__VariantsArgs;
export const PlasmicRelatedOffers__VariantProps = new Array<VariantPropType>();

export type PlasmicRelatedOffers__ArgsType = {
  otrasOfertas?: React.ReactNode;
  sliderButtons?: React.ReactNode;
  companyOffers?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRelatedOffers__ArgsType;
export const PlasmicRelatedOffers__ArgProps = new Array<ArgPropType>(
  "otrasOfertas",
  "sliderButtons",
  "companyOffers"
);

export type PlasmicRelatedOffers__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRelatedOffersProps {
  otrasOfertas?: React.ReactNode;
  sliderButtons?: React.ReactNode;
  companyOffers?: React.ReactNode;
  className?: string;
}

function PlasmicRelatedOffers__RenderFunc(props: {
  variants: PlasmicRelatedOffers__VariantsArgs;
  args: PlasmicRelatedOffers__ArgsType;
  overrides: PlasmicRelatedOffers__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__yHfPt)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Otras ofertas de Burger King S.A.",
          value: args.otrasOfertas,
          className: classNames(sty.slotTargetOtrasOfertas)
        })}

        {true ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__d1TKb)}
          >
            {p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button__p4UlY)}
                    type={"lastItemDisabled" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__ccRtm)}
                    type={"nextItem" as const}
                  />
                </React.Fragment>
              ),
              value: args.sliderButtons
            })}
          </p.Stack>
        ) : null}
      </p.Stack>

      <div className={classNames(projectcss.all, sty.freeBox__yiJvd)}>
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <OfferCard
                className={classNames("__wab_instance", sty.offerCard__j8Es)}
                insideOffer={true}
              />

              <OfferCard
                className={classNames("__wab_instance", sty.offerCard__ueHFf)}
                insideOffer={true}
              />

              <OfferCard
                className={classNames("__wab_instance", sty.offerCard__ciIFv)}
                insideOffer={true}
              />
            </React.Fragment>
          ),
          value: args.companyOffers
        })}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRelatedOffers__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRelatedOffers__VariantsArgs;
    args?: PlasmicRelatedOffers__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRelatedOffers__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRelatedOffers__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRelatedOffers__ArgProps,
          internalVariantPropNames: PlasmicRelatedOffers__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicRelatedOffers__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRelatedOffers";
  } else {
    func.displayName = `PlasmicRelatedOffers.${nodeName}`;
  }
  return func;
}

export const PlasmicRelatedOffers = Object.assign(
  // Top-level PlasmicRelatedOffers renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRelatedOffers
    internalVariantProps: PlasmicRelatedOffers__VariantProps,
    internalArgProps: PlasmicRelatedOffers__ArgProps
  }
);

export default PlasmicRelatedOffers;
/* prettier-ignore-end */
