// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicFooterSitemap,
  DefaultFooterSitemapProps
} from "./plasmic/open_bootcamp_v_2_0/PlasmicFooterSitemap";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface FooterSitemapProps extends Omit<DefaultFooterSitemapProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultFooterSitemapProps altogether and have
// total control over the props for your component.
export interface FooterSitemapProps extends DefaultFooterSitemapProps {}

function FooterSitemap_(
  props: FooterSitemapProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicFooterSitemap to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicFooterSitemap are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all FooterSitemapProps here, but feel free
  // to do whatever works for you.

  return <PlasmicFooterSitemap root={{ ref }} {...props} />;
}

const FooterSitemap = React.forwardRef(FooterSitemap_);
export default FooterSitemap;
